module.exports = {
    AUTO_VIEW_STATUS: 'false',
    AUTO_LIKE_STATUS: 'false',
    AUTO_RECORDING: 'false',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/BpxeV6YBGnY1jUvAgolqIE?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/f9gwsx.jpg',
    NEWSLETTER_JID: '120363402507750390@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝗠𝗟𝗧𝗡-𝗠𝟳',
    OWNER_NAME: '𝗠𝗲𝗹𝘁𝗼𝗻 𝗠𝟳',
    OWNER_NUMBER: '254112075297',
    BOT_VERSION: '1.0.2',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ 𝙼𝚎𝚕𝚝𝚘𝚗 𝙼𝟽',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb7HtHx9hXF4dENFNq2C',
};
